Repository openHPI/codeharbor, pull requests merged in 2024-02, with the labels that each got.

#1191 Making the collection task list sortable
  app/assets/javascripts/collections.coffee
  app/assets/stylesheets/collections.css.scss
  app/controllers/collections_controller.rb
  app/models/collection.rb
  app/views/collections/_collections.html.slim
  app/views/collections/_form.html.slim
  app/views/collections/show.html.slim
  config/locales/en/views/collections.yml
  db/migrate/20240111200306_add_rank_and_timestamp_to_collection_tasks.rb
  db/schema.rb
  spec/controllers/collections_controller_spec.rb
  spec/models/collection_spec.rb
Labels: enhancement

#1248 Disallowing group admins to destroy tasks they do not own
  app/policies/task_policy.rb
  spec/policies/task_policy_spec.rb
Labels: bug

#1238 Update webpack-dev-server default port to 3045
  Vagrantfile
  config/content_security_policy.yml.ci
  config/content_security_policy.yml.example
  config/shakapacker.yml
  docs/LOCAL_SETUP.md
  docs/LOCAL_SETUP_VAGRANT.md
Labels: enhancement, javascript
