Repository openHPI/codeharbor, pull requests merged in 2024-03, with the labels that each got.

#1281 Switch SAML development provider
  app/controllers/users/omniauth_callbacks_controller.rb
  config/certs/samltestid_certificate.pem
  config/certs/samltestid_key.pem
  config/initializers/content_security_policy.rb
  config/initializers/devise.rb
  config/settings/development.yml
  config/settings/production.yml
  config/settings/test.yml
  lib/omni_auth/strategies/mock_saml.rb
  lib/omni_auth/strategies/saml_test_id.rb
Labels: enhancement, ruby

#1240 Use Webpack to deliver newest ACE editor
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/editor.coffee
  app/javascript/application.js
  package.json
  yarn.lock
Labels: enhancement

#1319 Rebrush Advanced Search Elements
  app/assets/stylesheets/bootstrap_and_overrides.css.scss
  app/assets/stylesheets/buttons-and-controls.css.scss
  app/assets/stylesheets/exercises.css.scss
  app/views/tasks/index.html.slim
Labels: javascript
