Repository openHPI/codeharbor, pull requests merged in 2024-07, with the labels that each got.

#1491 LOM: Return description in HTML rather than Markdown
  app/services/lom_service/export_lom.rb
  spec/controllers/bridges/lom/tasks_controller_spec.rb
Labels: enhancement, ruby

#1489 Encourage users to respond to group requests
  app/views/access_request_mailer/send_access_request.html.erb
  config/locales/de/views/groups.yml
  config/locales/en/views/groups.yml
Labels: enhancement

#1326 Add sign-in flow with NBP Wallet
  Gemfile
  Gemfile.lock
  app/assets/javascripts/flash_message.coffee
  app/assets/javascripts/nbp_wallet.coffee
  app/assets/stylesheets/users.css.scss
  app/controllers/users/nbp_wallet_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/models/user.rb
  app/views/application/_footer.html.slim
  app/views/users/nbp_wallet/connect.html.slim
  app/views/users/registrations/edit.html.slim
  config/locales/de/common.yml
  config/locales/de/controllers/users.yml
  config/locales/de/views/application.yml
  config/locales/de/views/breadcrumbs.yml
  config/locales/de/views/users.yml
  config/locales/en/common.yml
  config/locales/en/controllers/users.yml
  config/locales/en/views/application.yml
  config/locales/en/views/breadcrumbs.yml
  config/locales/en/views/users.yml
  config/routes.rb
  config/settings/development.yml
  config/settings/production.yml
  config/settings/test.yml
  db/migrate/20240531161908_destroy_dangling_user_identities.rb
  db/schema.rb
  lib/enmeshed/api_schema.yml
  lib/enmeshed/attribute.rb
  lib/enmeshed/attribute/identity.rb
  lib/enmeshed/attribute/relationship.rb
  lib/enmeshed/connector.rb
  lib/enmeshed/identity_info.rb
  lib/enmeshed/object.rb
  lib/enmeshed/relationship.rb
  lib/enmeshed/relationship_template.rb
  lib/enmeshed/status_group_synonyms.yml
  spec/controllers/users/nbp_wallet_controller_spec.rb
  spec/controllers/users/omniauth_callbacks_controller_spec.rb
  spec/fixtures/files/enmeshed/display_name_created.json
  spec/fixtures/files/enmeshed/existing_display_name.json
  spec/fixtures/files/enmeshed/get_enmeshed_address.json
  spec/fixtures/files/enmeshed/invalid_role_relationship.json
  spec/fixtures/files/enmeshed/missing_attribute_relationship.json
  spec/fixtures/files/enmeshed/no_existing_display_name.json
  spec/fixtures/files/enmeshed/no_relationship_templates_yet.json
  spec/fixtures/files/enmeshed/no_relationships_yet.json
  spec/fixtures/files/enmeshed/relationship_expired.json
  spec/fixtures/files/enmeshed/relationship_impossible_attributes.json
  spec/fixtures/files/enmeshed/relationship_template_created.json
  spec/fixtures/files/enmeshed/valid_relationship_created.json
  spec/fixtures/files/enmeshed/valid_relationship_template_created.json
  spec/lib/enmeshed/attribute/relationship_spec.rb
  spec/lib/enmeshed/attribute_spec.rb
  spec/lib/enmeshed/connector_spec.rb
  spec/lib/enmeshed/relationship_template_spec.rb
  spec/models/user_spec.rb
Labels: enhancement

#1497 Refactor Collection Share menu to avoid adblocking
  app/assets/javascripts/collections.coffee
  app/assets/stylesheets/collections.css.scss
  app/views/collections/show.html.slim
Labels: bug, javascript

#1523 Add noreferrer policy for external links
  app/views/tasks/_import_actions.html.slim
  app/views/tasks/_import_dialog_content.html.slim
  config/locales/de/views/users.yml
  config/locales/en/views/users.yml
Labels: enhancement

#1524 Policy: Use no_one rather than false
  app/policies/application_policy.rb
  app/policies/task_policy.rb
Labels: enhancement

#1525 Titleize ActiveRecord attribute and model names
  config/locales/en/models.yml
  spec/controllers/users/omniauth_callbacks_controller_spec.rb
  spec/models/task_spec.rb
Labels: enhancement

#1537 Upgrade model from gpt3.5 to gpt4o-mini
  config/settings/development.yml
  config/settings/production.yml
  config/settings/test.yml
Labels: enhancement
