Repository openHPI/codeharbor, pull requests merged in 2024-09, with the labels that each got.

#1657 Allow moving ProFormA files between fileables
  app/models/concerns/file_concern.rb
  app/models/model_solution.rb
  app/models/task.rb
  app/models/task_file.rb
  app/models/test.rb
  app/services/proforma_service/convert_proforma_task_to_task.rb
  app/views/tasks/_nested_file_form.html.slim
  spec/services/proforma_service/convert_proforma_task_to_task_spec.rb
Labels: enhancement, data exchange, ruby

#1675 Rejecting or revoking a collection invite destroys the invitation
  app/controllers/collections_controller.rb
  app/models/message.rb
  config/locales/de/models.yml
  config/locales/en/models.yml
  spec/controllers/collections_controller_spec.rb
  spec/models/message_spec.rb
Labels: bug

#1684 GitHub Actions: Install required packages for specs
  .github/workflows/ci.yml
Labels: dependencies, ruby

#1625 Fix source map generation with Webpack
  config/webpack/webpack.config.js
Labels: bug, javascript
