Repository openHPI/codeharbor, pull requests merged in 2024-08, with the labels that each got.

#1496 Allow users to configure a personal OpenAI API key
  app/controllers/tasks_controller.rb
  app/controllers/users/registrations_controller.rb
  app/errors/gpt/error.rb
  app/errors/gpt/invalid_task_description.rb
  app/errors/gpt/missing_language_error.rb
  app/models/user.rb
  app/policies/task_policy.rb
  app/services/gpt_service/generate_tests.rb
  app/services/gpt_service/gpt_service_base.rb
  app/services/gpt_service/validate_api_key.rb
  app/views/tasks/show.html.slim
  app/views/users/registrations/edit.html.slim
  app/views/users/show.html.slim
  config/initializers/open_ai.rb
  config/locales/de/controllers/tasks.yml
  config/locales/de/errors.yml
  config/locales/de/models.yml
  config/locales/de/views/tasks.yml
  config/locales/de/views/users.yml
  config/locales/en/controllers/tasks.yml
  config/locales/en/errors.yml
  config/locales/en/models.yml
  config/locales/en/views/tasks.yml
  config/locales/en/views/users.yml
  config/settings/development.yml
  config/settings/production.yml
  config/settings/test.yml
  db/migrate/20240703221801_add_openai_api_key_to_users.rb
  db/schema.rb
  spec/controllers/tasks_controller_spec.rb
  spec/errors/gpt/error_spec.rb
  spec/models/user_spec.rb
  spec/policies/task_policy_spec.rb
  spec/services/gpt_service/generate_tests_spec.rb
  spec/services/gpt_service/validate_api_key_spec.rb
  spec/services/task_service/gpt_generate_tests_spec.rb
Labels: enhancement

#1490 Disable footnote backlinks in Markdown
  app/helpers/application_helper.rb
Labels: enhancement, ruby

#1565 Enable contenthash in CSS filenames for webpack assets
  config/webpack/webpack.config.js
Labels: bug

#1553 Use Bulk Enqueueing for ActiveJob
  app/jobs/nbp_sync_all_job.rb
Labels: enhancement

#1572 Align memorization of boolean values with CodeOcean
  lib/nbp/push_connector.rb
  spec/lib/nbp/push_connector_spec.rb
Labels: ruby
